version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: starDb
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      MONGO_URL: "mongodb://root:root@mongodb:27017/starDb"
      API_URL: "https://swapi.dev/api/people"
    command: npm start


  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"